"""add discount fields to booking and discountcode

Revision ID: 18a67ca96014
Revises: e47bbfe21cba
Create Date: 2026-01-20 20:14:26.636529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18a67ca96014'
down_revision = 'e47bbfe21cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_code_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.alter_column('buyer_custom_info',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'discount_codes', ['discount_code_id'], ['id'])

    with op.batch_alter_table('buyer_info_fields', schema=None) as batch_op:
        batch_op.alter_column('field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
        batch_op.alter_column('field_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_column('used_count')

    with op.batch_alter_table('buyer_info_fields', schema=None) as batch_op:
        batch_op.alter_column('field_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('field_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('buyer_custom_info',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_code_id')

    # ### end Alembic commands ###
