"""Add color to Trip

Revision ID: 92343e49c33b
Revises: cb1868c32e8d
Create Date: 2026-01-01 21:28:51.010854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92343e49c33b'
down_revision = 'cb1868c32e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
