"""Add registration_date to Trip

Revision ID: d8c58af30cc3
Revises: 18a67ca96014
Create Date: 2026-02-16 21:28:57.803848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8c58af30cc3'
down_revision = '18a67ca96014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
