"""Add booking_packages table

Revision ID: ee0669b90296
Revises: 6b25642b4e65
Create Date: 2026-01-06 21:23:09.141036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0669b90296'
down_revision = '6b25642b4e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check if booking_packages table already exists
    tables = inspector.get_table_names()
    if 'booking_packages' not in tables:
        op.create_table('booking_packages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('package_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('payment_plan_type', sa.String(length=20), nullable=True),
        sa.Column('amount_paid', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
        sa.ForeignKeyConstraint(['package_id'], ['trip_packages.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Check if package_id column exists before dropping
    columns = [col['name'] for col in inspector.get_columns('bookings')]
    if 'package_id' in columns:
        # For SQLite, we need to recreate the table to drop the foreign key
        # This is a simplified approach - in production, you might want a more robust solution
        with op.batch_alter_table('bookings', schema=None) as batch_op:
            batch_op.drop_column('package_id')

    trip_package_columns = [col['name'] for col in inspector.get_columns('trip_packages')]
    with op.batch_alter_table('trip_packages', schema=None) as batch_op:
        if 'max_per_booking' in trip_package_columns:
            batch_op.drop_column('max_per_booking')
        if 'min_per_booking' in trip_package_columns:
            batch_op.drop_column('min_per_booking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_per_booking', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('max_per_booking', sa.INTEGER(), server_default=sa.text('(10)'), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'trip_packages', ['package_id'], ['id'])

    op.drop_table('booking_packages')
    # ### end Alembic commands ###
