"""
本地 CI 前置：QA trip + E2E 用户 + 写入 tests/e2e/.env.e2e（gitignore）。
在 flask-app 目录运行: python local_tests/prepare_e2e_env.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
E2E_ENV = REPO / "tests" / "e2e" / ".env.e2e"


def _read_flask_env_value(key: str) -> str:
    env_path = ROOT / ".env"
    if not env_path.exists():
        return ""
    for line in env_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith(f"{key}="):
            return line.split("=", 1)[1].strip().strip("\"'")
    return ""


def run() -> bool:
    load_dotenv(ROOT / ".env")
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    from local_tests.setup_test_trip import run as setup_trip
    from local_tests.ensure_e2e_users import run as ensure_users

    if not setup_trip():
        print("[FAIL] setup_test_trip")
        return False
    if not ensure_users():
        print("[FAIL] ensure_e2e_users")
        return False

    admin_user = os.environ.get("E2E_ADMIN_USERNAME", "_e2e_admin")
    admin_pass = os.environ.get("E2E_ADMIN_PASSWORD", "e2e-admin-temp")
    staff_user = os.environ.get("E2E_STAFF_USERNAME", "_pytest_staff")
    staff_pass = os.environ.get("E2E_STAFF_PASSWORD", "pytest-staff-temp")
    stripe_secret = os.environ.get("STRIPE_SECRET_KEY") or _read_flask_env_value("STRIPE_SECRET_KEY")
    stripe_whsec = os.environ.get("STRIPE_WEBHOOK_SECRET") or _read_flask_env_value(
        "STRIPE_WEBHOOK_SECRET"
    )

    lines = [
        "# Auto-generated by flask-app/local_tests/prepare_e2e_env.py — do not commit",
        "E2E_BASE_URL=http://127.0.0.1:8080",
        "E2E_TRIP_SLUG=qa-payment-trip-2026",
        f"E2E_ADMIN_USERNAME={admin_user}",
        f"E2E_ADMIN_PASSWORD={admin_pass}",
        f"E2E_STAFF_USERNAME={staff_user}",
        f"E2E_STAFF_PASSWORD={staff_pass}",
        "E2E_DISCOUNT_CODE=QAZERO",
    ]
    if stripe_secret:
        lines.append(f"E2E_STRIPE_SECRET_KEY={stripe_secret}")
    if stripe_whsec:
        lines.append(f"E2E_STRIPE_WEBHOOK_SECRET={stripe_whsec}")

    E2E_ENV.parent.mkdir(parents=True, exist_ok=True)
    E2E_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] wrote {E2E_ENV} (secrets not printed)")
    return True


if __name__ == "__main__":
    sys.exit(0 if run() else 1)
